### ISSUE TITLE
Feature Request for Texplorer

### ISSUE THREAD

**Issue by Ottemis** [KFreon/KFreons-ME3Explorer#1]
I know you're rebuilding, but I figured I'd just drop this here.
I'd like to request a check/uncheck all option in Texplorer under Rebuild Database.
I often rescan a partial tree and am constantly clicking all checkboxes off.
If that would be possible, that'd be grand =)

This is the one I'm referring to:
![image](https://cloud.githubusercontent.com/assets/22038757/18420551/8227328a-7875-11e6-86e9-95e4c6db6374.png)

**Comment by KFreon** [comment]
Can do :)
