### ISSUE TITLE
MIP error replacing HMF_HIR_Cru_Norm

### ISSUE THREAD

**Issue by Ottemis** [KFreon/KFreons-ME3Explorer#2]
I'm cloning textures and I noticed one of them giving me issues when trying to replace.
I can replace it fine at original texture size but attempting to effectively upscale nets me this error:

![image](https://cloud.githubusercontent.com/assets/22038757/18421121/4b3d9964-7882-11e6-86f7-344d79cdee75.png)

I've included the texture under it, so you can see it's format and that it's Mipped. I've tested this on the original asset (loaded in a custom DLC mod AND in the vanilla gamefiles) as well, and I see the same issue there:

![image](https://cloud.githubusercontent.com/assets/22038757/18421203/543650c2-7884-11e6-95a2-c54778a2e42c.png)

**Comment by Ottemis** [comment]
Same with HMF_HIR_SCP_Pll_Norm:
![image](https://cloud.githubusercontent.com/assets/22038757/18421378/0be8da96-788a-11e6-91d1-b8de69f8f667.png)

HMF_HIR_Sar_Norm:
![image](https://cloud.githubusercontent.com/assets/22038757/18421389/453a1472-788a-11e6-81b6-04e2d546ea96.png)

I feel a pattern emerging =/ _shakes fist at scalp textures_

HMM_HIR_Gez_Norm:
![image](https://cloud.githubusercontent.com/assets/22038757/18421407/a06fc90e-788a-11e6-874e-b39a19b81a5d.png)

So not unique to Femshep either.

**Comment by KFreon** [comment]
Gonna close this one Otte since it's a fair while ago.
I assume it's fixed in the new one :D
